[build]
functions = "netlify/functions"
publish = "public" # Specify your build directory if applicable

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "*"
